namespace DepoWise.Infrastructure.Database.Migrations;

/// <summary>Yerel SQLite migration kataloğu (tek doğru kaynak, artan sürüm).</summary>
public static class MigrationCatalog
{
    public static IReadOnlyList<IMigration> All() => new IMigration[]
    {
        new Migration001_CoreSchema(),
        new Migration002_AuthSeed(),
        new Migration003_AppSettings(),
        new Migration004_Personnel(),
        new Migration005_Materials(),
        new Migration006_StockDocuments(),
        new Migration007_Vehicles(),
        new Migration008_Maintenance(),
        new Migration009_FuelDailyActivity(),
        new Migration010_Requests(),
        new Migration011_Sync(),
        new Migration012_Releases(),
        new Migration013_RememberTokens(),
        new Migration014_UserBranch(),
        new Migration015_UserButtonPermissions(),
        new Migration016_CompanyFields(),
        new Migration017_StockDocFields(),
        new Migration018_ReleaseDownloadUrl(),
        new Migration019_PermissionTemplates(),
        new Migration020_TemplateRole(),
        new Migration021_MachineQuota(),
        new Migration022_MachineIpUserQuota(),
        new Migration023_MachineIpV4V6(),
        new Migration024_BranchCodePassword(),
        new Migration025_MachineBranch(),
        new Migration026_UserViewAllBranches(),
        new Migration027_OperatingBranch(),
        new Migration028_DataConflicts(),
        new Migration029_TwoRoleModel(),
        new Migration030_SplitPermScreens(),
        new Migration031_AlertReads(),
        new Migration032_CompanyGrantLimits(),
        new Migration033_UserPersonnelLink(),
        new Migration034_FieldStaffAndTitles(),
        new Migration035_SplitRequestApproval(),
        new Migration036_RestrictedSuperAdmin(),
        new Migration037_GrantLevel(),
        new Migration038_CompanyMaxAdmins(),
        new Migration039_TemplateScope(),
        new Migration040_MaterialTemplates(),
        new Migration041_RoleGrantLimits(),
        new Migration042_MustChangePassword(),
        new Migration043_TemplateCompatibleVehicles(),
        new Migration044_SpecialCodeAndPurge(),
        new Migration045_CompanyLocalReset(),
        new Migration046_MachineReset(),
        new Migration047_UserListPreferences(),
        new Migration048_NormalizeMaterialType(),
        new Migration049_ListPreferenceExtras(),
        new Migration050_NormalizeLookupSpaces(),
        new Migration051_LookupLocked(),
        new Migration052_FuelRecipient(),
        new Migration053_PostgresTurkishCollations(),
        new Migration054_MaterialTemplateLink(),
        new Migration055_MaterialBranch(),
        new Migration056_ExportPermission(),
        new Migration057_StockChangeLog(),
        new Migration058_ListPreferencePinnedSort(),
        new Migration059_MaintenanceTeamStock(),
        new Migration060_RequestOperations(),
        new Migration061_RequestOperationFields(),
        new Migration062_ChildTableCompanyId(),
        new Migration063_UserUsernameActiveUnique(),
        new Migration064_StockBalanceLocation(),
        new Migration065_ScreenPlatformVisibility(),
        new Migration066_Parties(),
        new Migration067_Invoices(),
        new Migration068_Finance(),
        new Migration069_ReversalSyncStamp(),
        new Migration070_MenuLayout(),
        new Migration071_MenuSection(),
        new Migration072_RoleGrantLimitsCompany(),
        new Migration073_Projects(),
        new Migration074_DocumentFields(),
        new Migration075_Equipment(),
        new Migration076_Assignments(),
        new Migration077_CostCenters(),
        new Migration078_PurchaseOrders(),
        new Migration079_WorkOrders(),
        new Migration080_CalendarEvents(),
        new Migration081_Announcements(),
        new Migration082_OperationIdCompanyScope(),
        new Migration083_CustomReports(),
        new Migration084_Teams(),
        new Migration085_ApprovalChain(),
        new Migration086_EquipmentMaintenance(),
        new Migration087_FieldRequirements(),   // 2026-09-03 (kullanıcı onayı): alan zorunluluğu — yalnız ekleme
        new Migration088_EquipmentTypeLocked(),  // 2026-09-04 HATA DÜZELTMESİ: equipment_types.is_locked eksikti
        new Migration089_DocumentFields(),       // 2026-09-04 MUH-01b: yakıt dağıtımı + iki bakım tablosuna belge no — yalnız ekleme
        new Migration090_MaintenancePartyLink(),  // 2026-09-04 MUH-01c: bakımlara cari (dış servis sağlayıcısı) — yalnız ekleme
        new Migration091_ListIndexes(),           // 2026-09-04 FAZ I: liste sorgularının indeksleri — yalnız CREATE INDEX
        new Migration092_RolePermissions(),       // 2026-09-05 FAZ 3a (ADR-222): rol bazlı ALLOW — yalnız CREATE TABLE, boş doğar
        new Migration093_FieldProtections(),      // 2026-09-05 FAZ 3b (ADR-223): korumalı alanlar — yalnız CREATE TABLE, boş doğar
        new Migration094_ConflictSnapshots(),     // 2026-09-06 FAZ 4.4: çakışmada kazanan/kaybeden görüntüsü — yalnız ADD COLUMN
        new Migration095_UserContactFields(),     // 2026-09-06 kullanıcı isteği: e-posta · telefon · unvan · not — yalnız ADD COLUMN
        new Migration096_Chat(),                  // 2026-09-06 kullanıcı isteği: uygulama içi sohbet — CREATE TABLE (boş doğar) + ADD COLUMN
    };
}
