namespace DepoWise.Infrastructure.Database.Migrations;

/// <summary>Yerel SQLite migration kataloğu (tek doğru kaynak, artan sürüm).</summary>
public static class MigrationCatalog
{
    public static IReadOnlyList<IMigration> All() => new IMigration[]
    {
        new Migration001_CoreSchema(),
        new Migration002_AuthSeed(),
        new Migration003_AppSettings(),
        new Migration004_Personnel(),
        new Migration005_Materials(),
        new Migration006_StockDocuments(),
        new Migration007_Vehicles(),
        new Migration008_Maintenance(),
        new Migration009_FuelDailyActivity(),
        new Migration010_Requests(),
        new Migration011_Sync(),
        new Migration012_Releases(),
        new Migration013_RememberTokens(),
        new Migration014_UserBranch(),
        new Migration015_UserButtonPermissions(),
        new Migration016_CompanyFields(),
        new Migration017_StockDocFields(),
        new Migration018_ReleaseDownloadUrl(),
        new Migration019_PermissionTemplates(),
        new Migration020_TemplateRole(),
        new Migration021_MachineQuota(),
        new Migration022_MachineIpUserQuota(),
        new Migration023_MachineIpV4V6(),
        new Migration024_BranchCodePassword(),
        new Migration025_MachineBranch(),
        new Migration026_UserViewAllBranches(),
        new Migration027_OperatingBranch(),
        new Migration028_DataConflicts(),
        new Migration029_TwoRoleModel(),
        new Migration030_SplitPermScreens(),
        new Migration031_AlertReads(),
        new Migration032_CompanyGrantLimits(),
        new Migration033_UserPersonnelLink(),
        new Migration034_FieldStaffAndTitles(),
        new Migration035_SplitRequestApproval(),
        new Migration036_RestrictedSuperAdmin(),
        new Migration037_GrantLevel(),
        new Migration038_CompanyMaxAdmins(),
        new Migration039_TemplateScope(),
        new Migration040_MaterialTemplates(),
        new Migration041_RoleGrantLimits(),
        new Migration042_MustChangePassword(),
        new Migration043_TemplateCompatibleVehicles(),
        new Migration044_SpecialCodeAndPurge(),
        new Migration045_CompanyLocalReset(),
        new Migration046_MachineReset(),
        new Migration047_UserListPreferences(),
        new Migration048_NormalizeMaterialType(),
        new Migration049_ListPreferenceExtras(),
        new Migration050_NormalizeLookupSpaces(),
        new Migration051_LookupLocked(),
        new Migration052_FuelRecipient(),
        new Migration053_PostgresTurkishCollations(),
        new Migration054_MaterialTemplateLink(),
        new Migration055_MaterialBranch(),
        new Migration056_ExportPermission(),
        new Migration057_StockChangeLog(),
    };
}
